// @ts-check

export const TRANSFER_BASE_FEE_LAMPORTS = 5000n;
export const TRANSFER_PRIORITY_FEE_LAMPORTS = 1000n;
export const TRANSFER_FEE_RESERVE_LAMPORTS =
  TRANSFER_BASE_FEE_LAMPORTS + TRANSFER_PRIORITY_FEE_LAMPORTS;
